name: machine-learning
channels:
  - defaults
dependencies:
  - asn1crypto=1.3.0=py37_0
  - astroid=2.3.3=py37_0
  - attrs=19.3.0=py_0
  - backcall=0.1.0=py37_0
  - blas=1.0=mkl
  - bleach=3.1.0=py37_0
  - bokeh=1.4.0=py37_0
  - ca-certificates=2020.1.1=0
  - certifi=2019.11.28=py37_0
  - cffi=1.13.2=py37h7a1dbc1_0
  - chardet=3.0.4=py37_1003
  - click=7.0=py37_0
  - colorama=0.4.3=py_0
  - cryptography=2.8=py37h7a1dbc1_0
  - cycler=0.10.0=py37_0
  - cymem=1.31.2=py37he980bc4_0
  - cytoolz=0.9.0.1=py37hfa6e2cd_1
  - decorator=4.4.1=py_0
  - defusedxml=0.6.0=py_0
  - dill=0.2.9=py37_0
  - elasticsearch=7.0.4=py_0
  - entrypoints=0.3=py37_0
  - flask=1.1.1=py_0
  - freetype=2.9.1=ha9979f8_1
  - icc_rt=2019.0.0=h0cc432a_1
  - icu=58.2=ha66f8fd_1
  - idna=2.8=py37_0
  - importlib_metadata=1.4.0=py37_0
  - intel-openmp=2019.4=245
  - ipykernel=5.1.4=py37h39e3cac_0
  - ipython=7.11.1=py37h39e3cac_0
  - ipython_genutils=0.2.0=py37_0
  - isort=4.3.21=py37_0
  - itsdangerous=1.1.0=py37_0
  - jedi=0.16.0=py37_0
  - jinja2=2.10.3=py_0
  - joblib=0.14.1=py_0
  - jpeg=9b=hb83a4c4_2
  - jsonschema=3.2.0=py37_0
  - jupyter_client=5.3.4=py37_0
  - jupyter_core=4.6.1=py37_0
  - kiwisolver=1.1.0=py37ha925a31_0
  - krb5=1.16.4=hc04afaa_0
  - lazy-object-proxy=1.4.3=py37he774522_0
  - libpng=1.6.37=h2a8f88b_0
  - libpq=11.2=h3235a2c_0
  - libsodium=1.0.16=h9d3ae62_0
  - libtiff=4.1.0=h56a325e_0
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - markupsafe=1.1.1=py37he774522_0
  - matplotlib=3.1.1=py37hc8f65d3_0
  - mccabe=0.6.1=py37_1
  - mistune=0.8.4=py37he774522_0
  - mkl=2019.4=245
  - mkl-service=2.3.0=py37hb782905_0
  - mkl_fft=1.0.15=py37h14836fe_0
  - mkl_random=1.1.0=py37h675688f_0
  - more-itertools=8.0.2=py_0
  - msgpack-numpy=0.4.4.3=py_0
  - msgpack-python=0.5.6=py37he980bc4_1
  - msys2-conda-epoch=20160418=1
  - murmurhash=0.28.0=py37he025d50_0
  - nb_conda_kernels=2.2.2=py37_0
  - nbconvert=5.6.1=py37_0
  - nbformat=5.0.4=py_0
  - networkx=2.4=py_0
  - nltk=3.4.5=py37_0
  - notebook=6.0.3=py37_0
  - numpy=1.18.1=py37h93ca92e_0
  - numpy-base=1.18.1=py37hc3f5095_1
  - olefile=0.46=py37_0
  - openssl=1.1.1d=he774522_3
  - packaging=20.1=py_0
  - pandas=0.25.3=py37ha925a31_0
  - pandoc=2.2.3.2=0
  - pandocfilters=1.4.2=py37_1
  - parso=0.6.0=py_0
  - patsy=0.5.1=py37_0
  - pickleshare=0.7.5=py37_0
  - pillow=7.0.0=py37hcc1f983_0
  - pip=20.0.2=py37_1
  - plac=0.9.6=py37_0
  - preshed=1.0.1=py37he025d50_0
  - prometheus_client=0.7.1=py_0
  - prompt_toolkit=3.0.3=py_0
  - psycopg2=2.8.4=py37h7a1dbc1_0
  - pycparser=2.19=py37_0
  - pygments=2.5.2=py_0
  - pylint=2.4.4=py37_0
  - pyodbc=4.0.27=py37ha925a31_0
  - pyopenssl=19.1.0=py37_0
  - pyparsing=2.4.6=py_0
  - pyqt=5.9.2=py37h6538335_2
  - pyreadline=2.1=py37_1
  - pyrsistent=0.15.7=py37he774522_0
  - pysocks=1.7.1=py37_0
  - python=3.7.5=h8c8aaf0_0
  - python-dateutil=2.8.1=py_0
  - pytz=2019.3=py_0
  - pywin32=227=py37he774522_1
  - pywinpty=0.5.7=py37_0
  - pyyaml=5.2=py37he774522_0
  - pyzmq=18.1.0=py37ha925a31_0
  - qt=5.9.7=vc14h73c81de_0
  - regex=2018.07.11=py37hfa6e2cd_0
  - requests=2.22.0=py37_1
  - scikit-learn=0.21.3=py37h6288b17_0
  - scipy=1.3.2=py37h29ff71c_0
  - seaborn=0.9.0=pyh91ea838_1
  - send2trash=1.5.0=py37_0
  - setuptools=45.1.0=py37_0
  - sip=4.19.8=py37h6538335_0
  - six=1.14.0=py37_0
  - spacy=2.0.12=py37h8300f20_0
  - sqlalchemy=1.3.11=py37he774522_0
  - sqlite=3.30.1=he774522_0
  - statsmodels=0.10.1=py37h8c2d366_0
  - termcolor=1.1.0=py37_1
  - terminado=0.8.3=py37_0
  - testpath=0.4.4=py_0
  - thinc=6.10.3=py37h8300f20_0
  - tk=8.6.8=hfa6e2cd_0
  - toolz=0.10.0=py_0
  - tornado=6.0.3=py37he774522_0
  - tqdm=4.42.0=py_0
  - traitlets=4.3.3=py37_0
  - ujson=1.35=py37hfa6e2cd_0
  - urllib3=1.25.8=py37_0
  - vc=14.1=h0510ff6_4
  - vs2015_runtime=14.16.27012=hf0eaf9b_1
  - wcwidth=0.1.7=py37_0
  - webencodings=0.5.1=py37_1
  - werkzeug=0.16.1=py_0
  - wheel=0.34.1=py37_0
  - win_inet_pton=1.1.0=py37_0
  - wincertstore=0.2=py37_0
  - winpty=0.4.3=4
  - wrapt=1.10.11=py37hfa6e2cd_2
  - xz=5.2.4=h2fa13f4_4
  - yaml=0.1.7=hc54c509_2
  - zeromq=4.3.1=h33f27b4_3
  - zipp=0.6.0=py_0
  - zlib=1.2.11=h62dcd97_3
  - zstd=1.3.7=h508b16e_0
  - pip:
    - absl-py==0.8.1
    - cachetools==3.1.1
    - en-core-web-md==2.0.0
    - gast==0.2.2
    - google-auth==1.11.0
    - google-auth-oauthlib==0.4.1
    - google-pasta==0.1.8
    - gower==0.0.5
    - grpcio==1.26.0
    - h5py==2.10.0
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.0
    - markdown==3.1.1
    - oauthlib==3.1.0
    - opt-einsum==3.1.0
    - protobuf==3.11.2
    - pyarrow==0.15.1
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - requests-oauthlib==1.3.0
    - rsa==4.0
    - tensorboard==2.1.0
prefix: C:\ProgramData\Anaconda3\envs\machine-learning
